#!/usr/bin/env node

import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { execFileSync } from "node:child_process";
import { dirname, join, resolve } from "node:path";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(scriptDir, "..");
const distRoot = join(projectRoot, "dist");
const outputPath = join(distRoot, "agentpkg-cli-source.bundle.mjs");

function chunkText(value, size) {
  const chunks = [];
  for (let index = 0; index < value.length; index += size) {
    chunks.push(value.slice(index, index + size));
  }
  return chunks;
}

function createArchive() {
  const tempRoot = mkdtempSync(join(tmpdir(), "agentpkg-pack-"));
  const archivePath = join(tempRoot, "source.tar.gz");

  try {
    execFileSync(
      "tar",
      [
        "--exclude=./dist",
        "--exclude=./node_modules",
        "--exclude=./.git",
        "--exclude=./.DS_Store",
        "--exclude=.DS_Store",
        "-czf",
        archivePath,
        ".",
      ],
      {
        cwd: projectRoot,
        stdio: "inherit",
      },
    );
    return readFileSync(archivePath).toString("base64");
  } finally {
    rmSync(tempRoot, { recursive: true, force: true });
  }
}

mkdirSync(distRoot, { recursive: true });
const encodedArchive = createArchive();
const chunks = chunkText(encodedArchive, 76);
const output = [
  "// Generated by npm run pack:source. Do not edit by hand.",
  "export const sourceBundle = {",
  '  name: "agentpkg-cli",',
  '  format: "tar.gz+base64",',
  `  createdAt: ${JSON.stringify(new Date().toISOString())},`,
  "  data: [",
  ...chunks.map((chunk) => `    ${JSON.stringify(chunk)},`),
  '  ].join(""),',
  "};",
  "",
].join("\n");

writeFileSync(outputPath, output, "utf8");
process.stdout.write(`Wrote ${outputPath}\n`);
